backend:
  name: github
  repo: srividyaa-star/als-joint
  branch: main
  base_url: https://auth.decapcms.org # Helper for GitHub Auth on GH Pages

media_folder: "assets"
public_folder: "assets"

collections:
  - name: "menu"
    label: "Menu Sections"
    file: "menu.json"
    format: "json"
    fields:
      - label: "Sections"
        name: "sections"
        widget: "list"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description (Optional)", name: "description", widget: "string", required: false }
          - label: "Menu Items"
            name: "items"
            widget: "list"
            fields:
              - { label: "Item Name", name: "name", widget: "string" }
              - { label: "Price", name: "price", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
